auto: true

markdown: kramdown

kramdown:
  input: GFM

pygments: true
paginate: 10
permalink: /:title

# For RSS xml
title: laucherish's Blog
description: － laucherish's Blog －
url: http://laucherish.github.io
feed: /rss.xml
author_info: <a href="http://laucherish.github.io">laucherish</a>

# 作者信息，不要的就自己删除掉吧，以及about.html页面里面的。
author: 
  name: laucherish
  email: laucherish@163.com
  link: http://laucherish.github.io
  weibo: http://weibo.com/525072789

# gavatar头像及Favicon
gavatar: /public/img/logo_100x.png
favicon: http://lanternd.qiniudn.com/favicon.ico


# google analytics 设置
ga:
  id: UA-54601036-1
  url: http://dlyang.me
  userid: 54601036

disqus:
  shortname: lanternd

duoshuo:
  shortname: dlyang