auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: laucherish.github.io/
url: http://laucherish.github.io/
feed: /atom.xml
author_info: <a href="http://laucherish.github.io/">laucherish</a>
